[project]
authors = ["martinvuyk <martin.vuyklop@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "forge_tools"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = ">=25.3.0.dev2025040115,<26"
