[project]
authors = ["martinvuyk <martin.vuyklop@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Add a short description here"
name = "forge_tools"
platforms = ["osx-arm64", "linux-aarch64", "linux-64"]
version = "0.1.0"

[tasks]
build = { cmd = "./scripts/package-lib.sh" }
format = { cmd = "mojo format ./src" }
test = { cmd = "./scripts/test.sh" }
benchmark = { cmd = "./scripts/benchmark.sh" }

[dependencies]
max = ">=25.6.0.dev2025082605,<26"
